apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoblazorserverapp-deployment
spec:
  selector:
    matchLabels:
      app: demoblazorserverapp
  replicas: 1
  template:
    metadata:
      labels:
        app: demoblazorserverapp
    spec:
      containers:
      - name: demoblazorserverapp
        image: appimage.azurecr.io/cloudsmartops/demoblazorapp:35
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development 
        - name: DB_HOST
          value: demoappdb
        - name: DB_NAME
          value: DemoBlazorApp
        - name: DB_SA_PASSWORD
          value: Password@12345
        volumeMounts:
        - name: demoblazorserverapp-persistent-storage
          mountPath: /app/data
      volumes:
      - name: demoblazorserverapp-persistent-storage
        persistentVolumeClaim:
          claimName: demoblazorserverapp-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoappdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoappdb
  template:
    metadata:
      labels:
        app: demoappdb
    spec:
      securityContext:
        runAsUser: 0
      nodeSelector:
        agentpool: nodepoo1  
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        command: ['/bin/bash', '-c', '/opt/mssql/bin/sqlservr']
        ports:
          - containerPort: 1433
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development 
          - name: SA_PASSWORD
            value: Password@12345
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_TCP_PORT
            value: "1433"  
        volumeMounts:
          - name: demoappdb-persistent-storage
            mountPath: /var/opt/mssql
      volumes:
        - name: demoappdb-persistent-storage
          persistentVolumeClaim:
            claimName: demoappdb-pvc
 

---
apiVersion: v1
kind: Service
metadata:
  name: demoblazorserverapp-service
spec:
  selector:
    app: demoblazorserverapp
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer
 
 
---
apiVersion: v1
kind: Service
metadata:
  name: demoappdb-service
spec:
  selector:
    app: demoappdb
  ports:
  - name: sql
    port: 1433
    targetPort: 1433
  type: NodePort
 
 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demoblazorserverapp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demoappdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

